### PR TITLE
STOR-1700: Rebase `external-snapshotter` to v7.0.0 to get VolumeGroupSnapshot

### PR DESCRIPTION
**Pull request by mpatlasov**
Diff to upstream v7.0.0:
https://github.com/kubernetes-csi/external-snapshotter/compare/v7.0.0...mpatlasov:rebase-v7.0.0

Changes between 6.3.0 (OCP 4.15) and 7.0.0:

 * Add VolumeGroupSnapshot API definitions. (#814, @RaunakShah)
 * The VolumeGroupSnapshotSource.Selector is now an optional attribute, so that a pre-provisioned VolumeGroupSnapshotContent can be specified which does not require a matching label-selector. (#995, @nixpanic)
 * Update API for pre provisioned group snapshots (#971, @RaunakShah)
 * Create Volume functionality for volume group snapshots (Note: this feature is partially implemented and therefore it is not ready for use) (#826, @RaunakShah)
 * More detail printed columns output when get vgs/vgsc/vgsclass with kubectl (#865, @winrouter)
 * Webhooks for VolumeGroupSnapshot, VolumeGroupSnapshotContent and VolumeGroupSnapshotClass. (#825, @Rakshith-R)
 * Add finalizer to prevent deletion of individual volume snapshots that are part of a group (#972, @RaunakShah)
 * Delete individual snapshots as part of volume group snapshots delete API (#952, @RaunakShah)
 * Implement GetGroupSnapshotStatus so that pre-provisioned VolumeGroupSnapshots can be imported. (#837, @nixpanic)
 * Introduce logic to delete volume group snapshots (#882, @RaunakShah)

Full changelogs:

https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v7.0.0

@openshift/storage

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by bertinatto** [comment]
/lgtm cancel
@mpatlasov you might need to change the target branch.

**Comment by Phaow** [comment]
Pre verify passed with pre merged build `4.16.0-0.test-2024-02-07-024915-ci-ln-r3tf8xt-latest` (`build 4.16,openshift/csi-external-snapshotter#139`)
- Regression test with snapshot cases all look good
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/ginkgo-test/228606/console
```console
13 pass, 12 skip (13m45s)
```
- Tried with also contains https://github.com/openshift/cluster-csi-snapshot-controller-operator/pull/191 seems the `csi-snapshot-controller-operator-role` missed some permission, I manually mofified and enable the feature gate see the CRDs created as expected.
```console
$ oc logs csi-snapshot-controller-operator-7bfb6bbc6b-5pcsg| grep 'FeatureGates'| grep -i 'volume'
I0207 07:52:33.940035       1 event.go:364] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-cluster-storage-operator", Name:"csi-snapshot-controller-operator", UID:"198a6ece-98a9-4ab5-b038-4ed444ed9b4f", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'FeatureGatesInitialized' FeatureGates updated to featuregates.Features{Enabled:[]v1.FeatureGateName{"AdminNetworkPolicy", "AlibabaPlatform", "AutomatedEtcdBackup", "AzureWorkloadIdentity", "BuildCSIVolumes", "CSIDriverSharedResource", "CloudDualStackNodeIPs", "DNSNameResolver", "DynamicResourceAllocation", "ExternalCloudProvider", "ExternalCloudProviderAzure", "ExternalCloudProviderExternal", "ExternalCloudProviderGCP", "GCPClusterHostedDNS", "GCPLabelsTags", "GatewayAPI", "InsightsConfigAPI", "InstallAlternateInfrastructureAWS", "KMSv1", "MachineAPIProviderOpenStack", "MachineConfigNodes", "ManagedBootImages", "MaxUnavailableStatefulSet", "MetricsServer", "MixedCPUsAllocation", "NetworkLiveMigration", "NodeSwap", "OnClusterBuild", "OpenShiftPodSecurityAdmission", "PinnedImages", "PrivateHostedZoneAWS", "RouteExternalCertificate", "SignatureStores", "SigstoreImageVerification", "TranslateStreamCloseWebsocketRequests", "UpgradeStatus", "VSphereControlPlaneMachineSet", "VSphereStaticIPs", "ValidatingAdmissionPolicy", "VolumeGroupSnapshot"}, Disabled:[]v1.FeatureGateName{"ClusterAPIInstall", "DisableKubeletCloudCredentialProviders", "EventedPLEG", "MachineAPIOperatorDisableMachineHealthCheckController"}}
I0207 07:52:33.940091       1 starter.go:149] FeatureGates initialized: knownFeatureGates=[AdminNetworkPolicy AlibabaPlatform AutomatedEtcdBackup AzureWorkloadIdentity BuildCSIVolumes CSIDriverSharedResource CloudDualStackNodeIPs ClusterAPIInstall DNSNameResolver DisableKubeletCloudCredentialProviders DynamicResourceAllocation EventedPLEG ExternalCloudProvider ExternalCloudProviderAzure ExternalCloudProviderExternal ExternalCloudProviderGCP GCPClusterHostedDNS GCPLabelsTags GatewayAPI InsightsConfigAPI InstallAlternateInfrastructureAWS KMSv1 MachineAPIOperatorDisableMachineHealthCheckController MachineAPIProviderOpenStack MachineConfigNodes ManagedBootImages MaxUnavailableStatefulSet MetricsServer MixedCPUsAllocation NetworkLiveMigration NodeSwap OnClusterBuild OpenShiftPodSecurityAdmission PinnedImages PrivateHostedZoneAWS RouteExternalCertificate SignatureStores SigstoreImageVerification TranslateStreamCloseWebsocketRequests UpgradeStatus VSphereControlPlaneMachineSet VSphereStaticIPs ValidatingAdmissionPolicy VolumeGroupSnapshot]
$ oc get crd| grep volumegroupsnapshot
volumegroupsnapshotclasses.groupsnapshot.storage.k8s.io      2024-02-07T07:52:34Z
volumegroupsnapshotcontents.groupsnapshot.storage.k8s.io     2024-02-07T07:52:34Z
volumegroupsnapshots.groupsnapshot.storage.k8s.io            2024-02-07T07:52:34Z
```

**Pull request merged**
