### PR TITLE
STOR-1593: Rebase external-snapshotter to v8.0.1 for OCP 4.17

### PR DESCRIPTION
**Pull request by dfajmon**
Diff to upstream 8.0.1:
https://github.com/kubernetes-csi/external-snapshotter/compare/v8.0.1...dfajmon:rebase-8.0.1

Changes between 7.0.1 (OCP 4.16) and 8.0.1 (OCP 4.17):
- :warning: The validating logic for VolumeSnapshots, VolumeSnapshotContents, VolumeGroupSnapshots, and VolumeGroupSnapshotContents has been replaced by CEL validation rules. The validating webhook is now only being used for VolumeSnapshotClasses and VolumeGroupSnapshotClasses to ensure that there's at most one class per CSI Driver. The validation webhook is deprecated and will be removed in the next release. 
https://github.com/kubernetes-csi/external-snapshotter/pull/1091)
- Link the snapshotted PVCs and the corresponding PVs in VolumeGroupSnapshot and VolumeGroupSnapshotContent to make restoring data easier.
https://github.com/kubernetes-csi/external-snapshotter/pull/1069
- Update API for group snapshots, easing the restore process. https://github.com/kubernetes-csi/external-snapshotter/pull/1068
- https://github.com/kubernetes-csi/external-snapshotter/pull/1071
- https://github.com/kubernetes-csi/external-snapshotter/pull/1073
- https://github.com/kubernetes-csi/external-snapshotter/pull/1101 fixes https://github.com/kubernetes-csi/csi-lib-utils/issues/177
- This change will update the Restore size in volumesnapshotcontent to the size it's received from the CSI driver. If 0 is received, it won't be added to the Restore size as it means it is unspecified as per CSI spec. https://github.com/kubernetes-csi/external-snapshotter/pull/1011

Full changelogs:
https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v8.0.1

@openshift/storage

### CODE REVIEW

**Comment by duanwei33** [comment]
Need to take a look on the snapshot failed cases due to:

> {  fail [k8s.io/kubernetes@v1.30.1/test/e2e/storage/framework/snapshot_resource.go:75]: admission webhook "volumesnapshotclasses.snapshot.storage.k8s.io" denied the request: expect resource to be {snapshot.storage.k8s.io v1 volumesnapshotclasses}, but found {snapshot.storage.k8s.io v1 volumesnapshots}

**Comment by duanwei33** [comment]
The error comes from csi-snapshot-webhook, not sure why it admitting volumesnapshotclasses when creating the volumesnapshot.

> I0716 00:31:13.424783       1 webhook.go:131] handling request: {"kind":"AdmissionReview","apiVersion":"admission.k8s.io/v1","request":{"uid":"e4f2d61a-1a44-44a6-8503-ffe0c754964d","kind":{"group":"snapshot.storage.k8s.io","version":"v1","kind":"VolumeSnapshot"},"resource":{"group":"snapshot.storage.k8s.io","version":"v1","resource":"volumesnapshots"},"requestKind":{"group":"snapshot.storage.k8s.io","version":"v1","kind":"VolumeSnapshot"},"requestResource":{"group":"snapshot.storage.k8s.io","version":"v1","resource":"volumesnapshots"},"name":"mysnapshot","namespace":"wduan-snapshot","operation":"CREATE","userInfo":{"username":"system:admin","groups":["system:masters","system:authenticated"]},"object":{"apiVersion":"snapshot.storage.k8s.io/v1","kind":"VolumeSnapshot","metadata":{"creationTimestamp":"2024-07-16T00:31:13Z","generation":1,"managedFields":[{"apiVersion":"snapshot.storage.k8s.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{".":{},"f:source":{".":{},"f:persistentVolumeClaimName":{}},"f:volumeSnapshotClassName":{}}},"manager":"kubectl-create","operation":"Update","time":"2024-07-16T00:31:13Z"}],"name":"mysnapshot","namespace":"wduan-snapshot","uid":"d2851159-b30e-450a-ab51-7f74301334f7"},"spec":{"source":{"persistentVolumeClaimName":"mypvc-ori"},"volumeSnapshotClassName":"csi-aws-vsc"}},"oldObject":null,"dryRun":false,"options":{"kind":"CreateOptions","apiVersion":"meta.k8s.io/v1","fieldManager":"kubectl-create","fieldValidation":"Ignore"}}}
> I0716 00:31:13.424888       1 snapshot.go:52] admitting volumesnapshotclasses
> E0716 00:31:13.424902       1 snapshot.go:84] expect resource to be {snapshot.storage.k8s.io v1 volumesnapshotclasses}, but found {snapshot.storage.k8s.io v1 volumesnapshots}
> I0716 00:31:13.424936       1 webhook.go:177] sending response: &AdmissionReview{Request:nil,Response:&AdmissionResponse{UID:e4f2d61a-1a44-44a6-8503-ffe0c754964d,Allowed:false,Result:&v1.Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:,Message:expect resource to be {snapshot.storage.k8s.io v1 volumesnapshotclasses}, but found {snapshot.storage.k8s.io v1 volumesnapshots},Reason:,Details:nil,Code:0,},Patch:nil,PatchType:nil,AuditAnnotations:map[string]string{},Warnings:[],},}
>

**Comment by jsafrane** [comment]
The release note say:

> # Urgent Upgrade Notes
> ## (No, really, you MUST read this before you upgrade)
> The validating logic for VolumeSnapshots, VolumeSnapshotContents, VolumeGroupSnapshots, and VolumeGroupSnapshotContents has been replaced by CEL validation rules. The validating webhook is now only being used for VolumeSnapshotClasses and VolumeGroupSnapshotClasses to ensure that there's at most one class per CSI Driver. The validation webhook is deprecated and will be removed in the next release. (#1091, @leonardoce)

So, we need to rework the cluster-csi-snapshot-controller-operator a bit:
1. We need to update snapshot CRD definitions [there](https://github.com/openshift/cluster-csi-snapshot-controller-operator/tree/master/assets) with [the new CRDs](https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd) from external-snapshotter.
2. We need to update [the webhook config](https://github.com/openshift/cluster-csi-snapshot-controller-operator/blob/master/assets/webhook_config.yaml) there to [validate only VolumeSnapshotClasses and VolumeGroupSnapshotClasses](https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/webhook-example/admission-configuration-template).

**Comment by jsafrane** [comment]
@duanwei33 upstream has reworked the webhook - some validation is done by the API server directly, without the webhook. In general, users should see no difference.

**Comment by duanwei33** [comment]
Snapshot cases look good in CI.
We might need to update some validation test in QE's Polarion, we can do that later.

/label qe-approved

**Pull request merged**
