### PR TITLE
Bug 1993934: Merge upstream v4.2.0

### PR DESCRIPTION
**Pull request by bertinatto**
https://github.com/kubernetes-csi/external-snapshotter/compare/v4.2.0...bertinatto:merge-v4.2.0

CC @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/test e2e-gcp-csi
/test e2e-aws-csi
I don't like the snapshot failures

**Comment by jsafrane** [comment]
/test e2e-gcp-csi
/test e2e-aws-csi
just to be sure...

**Comment by jsafrane** [comment]
Something is wrong. In run https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_csi-external-snapshotter/56/pull-ci-openshift-csi-external-snapshotter-master-e2e-gcp-csi/1428026187141091328

* A test wants to create a snapshot at 16:51:34.497:
```
Aug 18 16:51:34.497: INFO: Waiting up to 5m0s for VolumeSnapshot snapshot-9qr8s to become ready
```

* But snapshot-controller logs its last line at 2021-08-18T16:50:04.903499802Z. What does it do for the rest of the job run? 
* Periodic 4.9 job doesn't show any recent breakage (yet): https://testgrid.k8s.io/redhat-openshift-ocp-release-4.9-broken#periodic-ci-openshift-release-master-nightly-4.9-e2e-gcp-csi

**Comment by jsafrane** [comment]
Reproduced on a cluster built from this PR. Just run snapshot tests 5x in parallel:

```
for i in `seq 5`; do ( TEST_CSI_DRIVER_FILES=manifest.yaml ./openshift-tests run openshift/csi  --run=VolumeSnapshotDataSource  |& tee log$i ) & done
```

Some tests timed out. Looking at the snapshot-controller container, all its `snapshotWorker` goroutines get stuck at:

```
goroutine 113 [semacquire, 13 minutes]:
sync.runtime_SemacquireMutex(0xc0004f59ec, 0x0, 0x1)
        /usr/lib/golang/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0004f59e8)
        /usr/lib/golang/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /usr/lib/golang/src/sync/mutex.go:81
github.com/kubernetes-csi/external-snapshotter/v4/pkg/metrics.(*operationMetricsManager).OperationStart(0xc0004f59e0, 0x19aba21, 0xe, 0xc000703e60, 0x24, 0xc0004b6050, 0xf, 0x19a600c, 0x7, 0x0, ...)
        /go/src/github.com/kubernetes-csi/external-snapshotter/pkg/metrics/metrics.go:186 +0x217
github.com/kubernetes-csi/external-snapshotter/v4/pkg/common-controller.(*csiSnapshotCommonController).processSnapshotWithDeletionTimestamp(0xc0005980f0, 0xc000732f00, 0xc000732f00, 0x0)
        /go/src/github.com/kubernetes-csi/external-snapshotter/pkg/common-controller/snapshot_controller.go:252 +0x3cf
github.com/kubernetes-csi/external-snapshotter/v4/pkg/common-controller.(*csiSnapshotCommonController).syncSnapshot(0xc0005980f0, 0xc000732f00, 0x19723a0, 0xc000732f00)
        /go/src/github.com/kubernetes-csi/external-snapshotter/pkg/common-controller/snapshot_controller.go:205 +0x1175
github.com/kubernetes-csi/external-snapshotter/v4/pkg/common-controller.(*csiSnapshotCommonController).updateSnapshot(0xc0005980f0, 0xc000732f00, 0x0, 0x0)
        /go/src/github.com/kubernetes-csi/external-snapshotter/pkg/common-controller/snapshot_controller_base.go:374 +0x326
github.com/kubernetes-csi/external-snapshotter/v4/pkg/common-controller.(*csiSnapshotCommonController).syncSnapshotByKey(0xc0005980f0, 0xc000703f50, 0x24, 0xc00044e000, 0x1)
        /go/src/github.com/kubernetes-csi/external-snapshotter/pkg/common-controller/snapshot_controller_base.go:230 +0xed7
github.com/kubernetes-csi/external-snapshotter/v4/pkg/common-controller.(*csiSnapshotCommonController).snapshotWorker(0xc0005980f0)
        /go/src/github.com/kubernetes-csi/external-snapshotter/pkg/common-controller/snapshot_controller_base.go:195 +0xf8
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0003c8000)
        /go/src/github.com/kubernetes-csi/external-snapshotter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0003c8000, 0x1b91080, 0xc00024c030, 0x1, 0xc00044e060)
        /go/src/github.com/kubernetes-csi/external-snapshotter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003c8000, 0x0, 0x0, 0x1, 0xc00044e060)
        /go/src/github.com/kubernetes-csi/external-snapshotter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc0003c8000, 0x0, 0xc00044e060)
        /go/src/github.com/kubernetes-csi/external-snapshotter/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/kubernetes-csi/external-snapshotter/v4/pkg/common-controller.(*csiSnapshotCommonController).Run
        /go/src/github.com/kubernetes-csi/external-snapshotter/pkg/common-controller/snapshot_controller_base.go:146 +0x305
```

**Comment by jsafrane** [comment]
The tests are pretty flaky upstream too: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-csi-external-snapshotter-1-21-on-kubernetes-1-21

**Comment by jsafrane** [comment]
I am testing a fix in https://github.com/openshift/csi-external-snapshotter/pull/57/commits/0f6dd486bb3b8d379156707d3bb52b14e0f4932d - metrics.go tries to acquire a mutex twice in the same goroutine and go mutexes are not recursive.

**Comment by jsafrane** [comment]
Reported upstream in https://github.com/kubernetes-csi/external-snapshotter/issues/580 for experimental patch. We may need to introduce https://github.com/kubernetes-csi/external-snapshotter/pull/581 here. I hope upstream is going to release a new version soon.

**Comment by bertinatto** [comment]
> Reported upstream in [kubernetes-csi#580](https://github.com/kubernetes-csi/external-snapshotter/issues/580). We may need to introduce [kubernetes-csi#581](https://github.com/kubernetes-csi/external-snapshotter/pull/581) here. I hope upstream is going to release a new version soon.

Done. Let's run the CSI jobs a few times before merging to make sure the flake is gone.

**Pull request merged**
