### PR TITLE
Rebase v4.1.0

### PR DESCRIPTION
**Pull request by Elbehery**
https://github.com/kubernetes-csi/external-snapshotter/compare/v4.1.0...Elbehery:rebase-v4.1.0

@openshift/storage @dobsonj

### CODE REVIEW

**Comment by Elbehery** [comment]
\retest

**Comment by dobsonj** [comment]
This test failure is different from the flaky AWS snapshot volume issue I was running into.
GCP is returning 503 when trying to authenticate for this test:
```
INFO[2021-05-04T16:46:02Z] level=fatal msg=failed to fetch Cluster: failed to fetch dependency of "Cluster": failed to generate asset "Platform Quota Check": failed to load Quota for services: projects/**********************/services/compute.googleapis.com, projects/**********************/services/iam.googleapis.com: failed to load quota limits: googleapi: Error 503: Authentication backend unavailable., backendError 
```
It failed the same way both times... maybe there is a temporary issue with the GCP service?

**Comment by Elbehery** [comment]
> Error

yes I have checked the logs, most of the tests are `jUnit` and mainly failing to `dial` other endpoints. 
Shall we just wait and try again later or ?

**Comment by jsafrane** [comment]
`failed to load quota limits: googleapi: Error 503: Authentication backend unavailable., backendError` - installation failed, looks unrelated to this PR
/retest

**Pull request closed without merging**
