### PR TITLE
Bug 2043130: Update CSI sidecars to the latest release for 4.10

### PR DESCRIPTION
**Pull request by dobsonj**
This rebases on v5.0.1 upstream, bumps the Dockerfiles to the golang 1.17 images, and removes 2 stale Dockerfiles that have not been updated in some time (`Dockerfile.openshift.rhel7` and `Dockerfile.snapshot-controller.openshift`).
The Dockerfile changes replace the need for these 3 ART PR's, which were blocked until upstream moved to golang 1.17:
- https://github.com/openshift/csi-external-snapshotter/pull/63
- https://github.com/openshift/csi-external-snapshotter/pull/64
- https://github.com/openshift/csi-external-snapshotter/pull/65

Upstream comparison: https://github.com/kubernetes-csi/external-snapshotter/compare/v5.0.1...dobsonj:bug2043130
/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
/hold
Test failure from https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_csi-external-snapshotter/66/pull-ci-openshift-csi-external-snapshotter-master-e2e-aws-csi/1484224021531725824/artifacts/e2e-aws-csi/gather-extra/artifacts/pods/openshift-cluster-csi-drivers_aws-ebs-csi-driver-controller-798f66c9d-8tdw8_csi-snapshotter.log
```
E0120 19:12:25.163042       1 snapshot_controller.go:107] createSnapshot for content [snapcontent-66d2d434-f61a-4eb4-bfc3-97ea04820a36]: error occurred in createSnapshotWrapper: failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-66d2d434-f61a-4eb4-bfc3-97ea04820a36: "snapshot controller failed to update snapcontent-66d2d434-f61a-4eb4-bfc3-97ea04820a36 on API server: volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-66d2d434-f61a-4eb4-bfc3-97ea04820a36\" is forbidden: User \"system:serviceaccount:openshift-cluster-csi-drivers:aws-ebs-csi-driver-controller-sa\" cannot patch resource \"volumesnapshotcontents\" in API group \"snapshot.storage.k8s.io\" at the cluster scope"
```
This is from the "Breaking Change" in the release notes for v5.0.1:
```
Replaces many VolumeSnapshot/VolumeSnapshotContent Update/UpdateStatus operations with Patch. This lowers the probability of the "object has been modified" update API errors occurring. This change introduces a dependency on two new RBAC rules for the CSI snapshotter sidecar: volumesnapshotcontents:patch, volumesnapshotcontents/status:patch and four new RBAC rules for the snapshot-controller: volumesnapshotcontents:patch, volumesnapshotcontents/status:patch, volumesnapshots:patch, and volumesnapshots/status: patch.
```

**Comment by jsafrane** [comment]
/hold cancel
All CSI driver operators were updated with the new RBACs. 
/lgtm

**Pull request merged**
